kotlin.code.style=official

## 强制关闭 Kotlin Native
#kotlin.native.enabled=false
#
## 忽略 Native Target 检测
#kotlin.native.ignoreDisabledTargets=true
#
## 禁止 Native 依赖传播
#kotlin.native.enableDependencyPropagation=false
#
## 禁止 CInterop Commonization
#kotlin.mpp.enableCInteropCommonization=false
#
## 禁止从 Maven 下载 Kotlin Native
#kotlin.native.distribution.downloadFromMaven=false
#
## 忽略错误的 Native 依赖
#kotlin.native.ignoreIncorrectDependencies=true